### ISSUE TITLE
Can't open pdf's 

### ISSUE THREAD

**Issue by emiliogonzalezjr** [CDrummond/lms-material-app#35]
I am using version 0.8.2 on a Samsung Galaxy A54 and with a pixel tablet.

When I try to open a pdf in the Lyrion app the following message appears:

>Do not have permissions to run Termux commands

I don't understand why I need termux to open a pdf, a pdf reader app is not enough?
In the lyrion app I can open .txt files, when I select the .txt file it open in my default browser, isn't this the expect behavior for the .pdf files as well?

I install Termux and setup the squeezelite app there. I can play musics with the Lyrion app through the Squeezelite app without problens. I can start and stop the squeezelite app with the lyrion app but I can't open a pdf, am I missing something? Is something that need to be configure in the app in order to be able to open pdf's?

![Screenshot_20241020_102209_Lyrion](https://github.com/user-attachments/assets/26145938-4301-4e0b-84af-7dc039b22d0e)

**Comment by CDrummond** [comment]
The error message is wrong - silly copy and paste error on my part. However, this only happens if there was an error launching the PDF viewer. Might be I need to ask for anther permission, I'll investigate when I get time.

**Comment by emiliogonzalezjr** [comment]
Just to give you more information, when I acess my LMS server with my mobile browser (firefox), I can open my pdf without problems.

**Comment by CDrummond** [comment]
When opening a PDF this app simply asks Android to open the PDF URL in whatever app is assigned to open PDFs. This works on my device, so I'm guessing you have no external PDF handler application. For 0.8.3 I've updated the code to check for a PDF handler and show an error if none found.

**Comment by emiliogonzalezjr** [comment]
Hi, I tested the 0.8.3 version and, although the message is now correct (no PDF handler found), I still can't open PDF's. I tested with several pdf viewers installed and still can't open pdf's from the Lyrion app. Is there something that I still need to do in order to make it work?

![Screenshot_20241103_125132_Lyrion](https://github.com/user-attachments/assets/74d32000-30ae-41f3-a607-4a5fbd98f339)

**Comment by CDrummond** [comment]
Sorry, but all I can say is it works for me. No idea why its not working for you, but I can't test on all devices, android versions, PDF viewers, etc. Sorry, but I just do not have the time...

**Comment by emiliogonzalezjr** [comment]
Just out of curiosity which android version and device are you testing the app? Wich pdf viewer app are you using? I trying with two diferent devices without luck (pixel tablet and a galaxy a54). I really apreciate the app and your work and I apologize if I appeared to be rude, english is not my native language. Unfortanely I don't know how to code but I'm available to test things if you need.

**Comment by CDrummond** [comment]
No need to apologize, you are not being rude - and you English is excellent! Far, far, better than I'd be in yours!

I'm using an S22 on Android 14. Just using the Samsung PDF viewer that came with the OS.

**Comment by emiliogonzalezjr** [comment]
I discover the problem... I install the lyrion app in my mon's phone and the pdf worked as expected (0.8.2 version). So, the problem of my devices is that none of the open source pdf viewers that I use work to open pdf from the lyrion app. My suspect is that they only open pdf files itself but can't open the link provided by the Lyrion app. The solution was to install the google drive app. The only think that I found strange is that firefox doesnt advertise itself to open the link of the pdf from the lyrion app, but it opens the .txt files from the app. Anyway, the google drive app solve the problem. Thank you for your time and your patience.
